package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.triggers.VcsTrigger
import jetbrains.buildServer.configs.kotlin.v2018_2.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = '03DeployToStaging'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("03DeployToStaging")) {
    triggers {
        val trigger1 = find<VcsTrigger> {
            vcs {
                branchFilter = ""
            }
        }
        trigger1.apply {
            perCheckinTriggering = true
            enableQueueOptimization = false
        }
    }
}
